[project]
name = "fastapi-course"
version = "0.1.0"
description = "FastAPI Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.135.2",
    "pytest>=9.0.3",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.7",
    "sqlalchemy>=2.0.48",
    "sqlmodel>=0.0.37",
    "tzdata>=2025.3",
]
